-- MySQL Script generated by MySQL Workbench
-- 09/09/16 04:15:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema juicd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema juicd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `juicd` DEFAULT CHARACTER SET latin1 ;
USE `juicd` ;

-- -----------------------------------------------------
-- Table `juicd`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juicd`.`customers` (
  `customerID` INT(12) NOT NULL,
  `cnameFirst` VARCHAR(45) NOT NULL,
  `cnameLast` VARCHAR(45) NOT NULL,
  `points` INT(8) NOT NULL,
  `email` VARCHAR(254) NULL DEFAULT NULL,
  PRIMARY KEY (`customerID`),
  UNIQUE INDEX `customerID_UNIQUE` (`customerID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juicd`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juicd`.`staff` (
  `staffID` INT(12) NOT NULL AUTO_INCREMENT,
  `snameFirst` VARCHAR(45) NOT NULL,
  `snameLast` VARCHAR(45) NOT NULL,
  `staffRank` VARCHAR(30) NOT NULL,
  `reportsTo` INT(12) NOT NULL,
  PRIMARY KEY (`staffID`),
  UNIQUE INDEX `staffID_UNIQUE` (`staffID` ASC),
  INDEX `fk_staff_idx` (`reportsTo` ASC),
  CONSTRAINT `fk_staff`
    FOREIGN KEY (`reportsTo`)
    REFERENCES `juicd`.`staff` (`staffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juicd`.`outlets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juicd`.`outlets` (
  `outletID` INT(8) NOT NULL AUTO_INCREMENT,
  `outletName` VARCHAR(45) NOT NULL,
  `managerID` INT(12) NOT NULL,
  PRIMARY KEY (`outletID`),
  UNIQUE INDEX `outletID_UNIQUE` (`outletID` ASC),
  INDEX `fk_outlets_staff1_idx` (`managerID` ASC),
  CONSTRAINT `fk_outlets_staff1`
    FOREIGN KEY (`managerID`)
    REFERENCES `juicd`.`staff` (`staffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juicd`.`worksAt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juicd`.`worksAt` (
  `staffID` INT(12) NOT NULL,
  `outletID` INT(8) NOT NULL,
  `percentage` DOUBLE NOT NULL,
  PRIMARY KEY (`staffID`, `outletID`),
  INDEX `fk_staff_has_outlets_outlets1_idx` (`outletID` ASC),
  INDEX `fk_staff_has_outlets_staff1_idx` (`staffID` ASC),
  CONSTRAINT `fk_staff_has_outlets_staff1`
    FOREIGN KEY (`staffID`)
    REFERENCES `juicd`.`staff` (`staffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_has_outlets_outlets1`
    FOREIGN KEY (`outletID`)
    REFERENCES `juicd`.`outlets` (`outletID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juicd`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juicd`.`orders` (
  `orderID` INT(12) NOT NULL,
  `customerID` INT(12) NOT NULL,
  `staffID` INT(12) NOT NULL,
  `outletID` INT(8) NOT NULL,
  `timedate` DATETIME NOT NULL,
  `day` ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') NOT NULL,
  PRIMARY KEY (`orderID`),
  UNIQUE INDEX `salesID_UNIQUE` (`orderID` ASC),
  INDEX `fk_orders_customers_idx` (`customerID` ASC),
  INDEX `fk_orders_worksAt_idx` (`staffID` ASC, `outletID` ASC),
  CONSTRAINT `fk_orders_customers`
    FOREIGN KEY (`customerID`)
    REFERENCES `juicd`.`customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_worksAt`
    FOREIGN KEY (`staffID` , `outletID`)
    REFERENCES `juicd`.`worksAt` (`staffID` , `outletID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juicd`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juicd`.`items` (
  `itemID` INT(12) NOT NULL,
  `itemName` VARCHAR(45) NOT NULL,
  `itemPrice` DOUBLE NOT NULL,
  `comments` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`itemID`),
  UNIQUE INDEX `itemID_UNIQUE` (`itemID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juicd`.`ingredientsJuice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juicd`.`ingredientsJuice` (
  `ingredientName` VARCHAR(45) NOT NULL,
  `unitPrice/ML` DOUBLE NOT NULL,
  PRIMARY KEY (`ingredientName`),
  UNIQUE INDEX `ingredientName_UNIQUE` (`ingredientName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juicd`.`hasItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juicd`.`hasItems` (
  `orders_orderID` INT(12) NOT NULL,
  `itemID` INT(12) NOT NULL,
  `itemQuantity` INT(4) NOT NULL,
  PRIMARY KEY (`orders_orderID`, `itemID`),
  INDEX `fk_hasItems_items_idx` (`itemID` ASC),
  INDEX `fk_hasItems_orders_idx` (`orders_orderID` ASC),
  CONSTRAINT `fk_hasItems_orders`
    FOREIGN KEY (`orders_orderID`)
    REFERENCES `juicd`.`orders` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hasItems_items`
    FOREIGN KEY (`itemID`)
    REFERENCES `juicd`.`items` (`itemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juicd`.`isJuice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juicd`.`isJuice` (
  `itemID` INT(12) NOT NULL,
  `ingredientName` VARCHAR(45) NOT NULL,
  `ingredientQuantity` INT(4) NOT NULL,
  `cupSize` INT(4) NULL,
  PRIMARY KEY (`itemID`, `ingredientName`),
  INDEX `fk_isJuice_ingredientsJuice_idx` (`ingredientName` ASC),
  INDEX `fk_isJuice_items_idx` (`itemID` ASC),
  CONSTRAINT `fk_items_has_ingredientsJuice_items1`
    FOREIGN KEY (`itemID`)
    REFERENCES `juicd`.`items` (`itemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_has_ingredientsJuice_ingredientsJuice1`
    FOREIGN KEY (`ingredientName`)
    REFERENCES `juicd`.`ingredientsJuice` (`ingredientName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
