-- MySQL Script generated by MySQL Workbench
-- 08/26/16 15:49:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Project1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Project1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Project1` DEFAULT CHARACTER SET utf8 ;
USE `Project1` ;

-- -----------------------------------------------------
-- Table `Project1`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project1`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique ID for Customer\n',
  `points` INT NOT NULL COMMENT '# Of Juic\'d Points',
  `newsletter` TINYINT(1) NOT NULL COMMENT 'Subscribed to Newsletter T/F',
  `email` VARCHAR(254) NULL COMMENT 'Email Address\n',
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project1`.`outlets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project1`.`outlets` (
  `outlet_id` INT NOT NULL AUTO_INCREMENT,
  `shopping centre` VARCHAR(45) NOT NULL,
  `manager` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`outlet_id`),
  UNIQUE INDEX `outlet_id_UNIQUE` (`outlet_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project1`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project1`.`staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `manager_id` INT NULL,
  `outlet_id` INT NULL,
  `timespent` DOUBLE NULL,
  PRIMARY KEY (`staff_id`),
  UNIQUE INDEX `staff_id_UNIQUE` (`staff_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
